name: End-to-end tests
on: [push]

jobs:
  e2e:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v5
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        wait-on-timeout: 120 
    - name: Upload Diff
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-diff
        path: cypress/diff/
    - name: Upload Origin
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-origin
        path: cypress/fixtures/
    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: cypress/screenshots/
